// AmeriCommerce Customer types
export interface AmeriCommerceCustomer {
  id?: string;
  email?: string;
  first_name?: string;
  last_name?: string;
  company?: string;
  phone?: string;
  address1?: string;
  address2?: string;
  city?: string;
  state?: string;
  zip?: string;
  country?: string;
  [key: string]: any; // For any additional fields
}

// Shopify Customer types
export interface ShopifyCustomer {
  'First Name': string;
  'Last Name': string;
  'Email': string;
  'Company': string;
  'Address1': string;
  'Address2': string;
  'City': string;
  'Province': string;
  'Province Code': string;
  'Country': string;
  'Country Code': string;
  'Zip': string;
  'Phone': string;
  'Accepts Marketing': string;
  'Tags': string;
}

// AmeriCommerce Order types
export interface AmeriCommerceOrder {
  id?: string;
  order_number?: string;
  customer_id?: string;
  customer_email?: string;
  customer_first_name?: string;
  customer_last_name?: string;
  order_date?: string;
  order_status?: string;
  payment_method?: string;
  shipping_method?: string;
  subtotal?: string;
  tax_total?: string;
  shipping_total?: string;
  discount_total?: string;
  grand_total?: string;
  [key: string]: any; // For any additional fields
}

// Shopify Order types
export interface ShopifyOrder {
  'Name': string;
  'Email': string;
  'Financial Status': string;
  'Fulfillment Status': string;
  'Currency': string;
  'Buyer Accepts Marketing': string;
  'Lineitem quantity': string;
  'Lineitem name': string;
  'Lineitem price': string;
  'Lineitem compare at price': string;
  'Lineitem sku': string;
  'Lineitem requires shipping': string;
  'Lineitem taxable': string;
  'Lineitem fulfillment status': string;
  'Billing Name': string;
  'Billing Street': string;
  'Billing Address1': string;
  'Billing Address2': string;
  'Billing Company': string;
  'Billing City': string;
  'Billing Zip': string;
  'Billing Province': string;
  'Billing Country': string;
  'Billing Phone': string;
  'Shipping Name': string;
  'Shipping Street': string;
  'Shipping Address1': string;
  'Shipping Address2': string;
  'Shipping Company': string;
  'Shipping City': string;
  'Shipping Zip': string;
  'Shipping Province': string;
  'Shipping Country': string;
  'Shipping Phone': string;
  'Notes': string;
  'Note Attributes': string;
  'Cancelled at': string;
  'Payment Method': string;
  'Payment Reference': string;
  'Refunded Amount': string;
  'Vendor': string;
  'Id': string;
  'Tags': string;
  'Risk Level': string;
  'Source': string;
  'Discount Code': string;
  'Discount Amount': string;
  'Shipping Method': string;
  'Created at': string;
  'Processed at': string;
  'Total': string;
  'Tax': string;
  'Shipping': string;
}

// AmeriCommerce Product types
export interface AmeriCommerceProduct {
  ItemID?: string;
  ItemNumber?: string;
  ItemName?: string;
  CategoryList?: string;
  CategoryListIDs?: string;
  ProductStatus?: string;
  Bullets?: string;
  ShortDescriptionForCategoryList?: string;
  BasePrice?: string;
  RetailPrice?: string;
  Cost?: string;
  Manufacturer?: string;
  ManufacturerPartNumber?: string;
  AdvancedPricing?: string;
  ItemImages?: string;
  ItemPrimaryImageUrl?: string;
  ItemPrimaryImageAltText?: string;
  ItemThumbnailUrl?: string;
  ItemThumbnailAltText?: string;
  UseTabs?: string;
  UseTabsThemesOverride?: string;
  RelatedProductNameOverride?: string;
  LongDescription1?: string;
  LongDescriptionName1?: string;
  LongDescription2?: string;
  LongDescriptionName2?: string;
  LongDescription3?: string;
  LongDescriptionName3?: string;
  LongDescription4?: string;
  LongDescriptionName4?: string;
  LongDescription5?: string;
  LongDescriptionName5?: string;
  LongDesc1ExternalUrl?: string;
  LongDesc2ExternalUrl?: string;
  LongDesc3ExternalUrl?: string;
  LongDesc4ExternalUrl?: string;
  LongDesc5ExternalUrl?: string;
  BulletsExternalUrl?: string;
  SizeHeight?: string;
  SizeLength?: string;
  SizeWidth?: string;
  SizeUnit?: string;
  Weight?: string;
  WeightUnit?: string;
  MinimumOrderQuantity?: string;
  MaximumOrderQuantity?: string;
  WarehouseName?: string;
  CallForShippingFlag?: string;
  ShipsIndividually?: string;
  NonShippingItem?: string;
  CallForPricingFlag?: string;
  NoTax?: string;
  CustomMetaKeywords?: string;
  CustomMetaDescription?: string;
  CustomPageTitle?: string;
  InactiveStoreList?: string;
  QuickBooksListID?: string;
  IsQuickBooksGroup?: string;
  SortOrder?: string;
  Variation1Group?: string;
  Variation1Description?: string;
  Variation1Surcharge?: string;
  Variation1SurchargeType?: string;
  Variation1ItemNumberExtension?: string;
  Variation2Group?: string;
  Variation2Description?: string;
  Variation2Surcharge?: string;
  Variation2SurchargeType?: string;
  Variation2ItemNumberExtension?: string;
  Variation3Group?: string;
  Variation3Description?: string;
  Variation3Surcharge?: string;
  Variation3SurchargeType?: string;
  Variation3ItemNumberExtension?: string;
  QuantityDiscount1Quantity?: string;
  QuantityDiscount1Price?: string;
  QuantityDiscount2Quantity?: string;
  QuantityDiscount2Price?: string;
  QuantityDiscount3Quantity?: string;
  QuantityDiscount3Price?: string;
  QuantityDiscount4Quantity?: string;
  QuantityDiscount4Price?: string;
  QuantityDiscount5Quantity?: string;
  QuantityDiscount5Price?: string;
  QuantityDiscount6Quantity?: string;
  QuantityDiscount6Price?: string;
  QuantityDiscount7Quantity?: string;
  QuantityDiscount7Price?: string;
  QuantityDiscount8Quantity?: string;
  QuantityDiscount8Price?: string;
  QuantityDiscount9Quantity?: string;
  QuantityDiscount9Price?: string;
  QuantityDiscount10Quantity?: string;
  QuantityDiscount10Price?: string;
  SpotLightItem?: string;
  FeaturedItem?: string;
  CustomFlag1?: string;
  CustomFlag2?: string;
  CustomFlag3?: string;
  DuplicateRowOnlyAddCategoryData?: string;
  OverwriteAllDataWithThisRow?: string;
  Hide?: string;
  AttributeList?: string;
  ProductUrl?: string;
  CustomUrl?: string;
  RelatedItemsList?: string;
  ProductGroup?: string;
  ProductGroupType?: string;
  NumberInStock?: string;
  OnOrderQuantity?: string;
  LowStockQuantity?: string;
  LowStockWarningsEnabled?: string;
  LimitShippingRegion?: string;
  BreakOutShipping?: string;
  ShippingClassificationCode?: string;
  CallForShippingWholeOrder?: string;
  DropShipping?: string;
  DeleteProduct?: string;
  Discontinued?: string;
  ETADate?: string;
  ShippingAdjustmentType?: string;
  ShippingAdjustments?: string;
  TaxCode?: string;
  UseMapPricing?: string;
  LastItemNr?: string;
  DoNotDiscount?: string;
  Personalizations?: string;
  HeadTags?: string;
  HandlingFee?: string;
  eProductType?: string;
  eProductDeliveryLinkAction?: string;
  eProductRandomExpireDays?: string;
  eProductMultipleDelivery?: string;
  eProductURL?: string;
  eProductEmail?: string;
  eProductSerialNumberFilePath?: string;
  CustomUpsellPageURL?: string;
  MultiplesOfQuantity?: string;
  StartingQuantity?: string;
  GTIN?: string;
  IsSubscriptionProduct?: string;
  SubscriptionFrequency?: string;
  SubscriptionFrequencyType?: string;
  RequireCreditCard?: string;
  NonInventory?: string;
  ExcludeFromCommissions?: string;
  AddToCartMessage?: string;
  NoPriceMask?: string;
  DaysUntilReorderAllowed?: string;
  ForceSeparateOrder?: string;
  ApprovalRequired?: string;
  EarnsPoints?: string;
  InelligibleForPurchaseByPoints?: string;
  AdditionalPointsEarned?: string;
  SalesRank?: string;
  HideVariantSurcharges?: string;
  MasterProduct?: string;
  Layouts?: string;
  EProductGenericUsername?: string;
  EProductGenericPassword?: string;
  VendorStoreId?: string;
  ShipperHQShippingGroups?: string;
  ShipperHQDimensionalRuleGroups?: string;
  ShipperHQPackingBoxes?: string;
  ShipperHQOrigins?: string;
  FreightClass?: string;
  HSCode?: string;
  IsExemptFromMinOrderAmount?: string;
  BingAdsGrouping?: string;
  BingAdsLabels?: string;
  Bingads_redirect?: string;
  BingExclude?: string;
  BingProductCategory?: string;
  DealExpiration?: string;
  DealStartDate?: string;
  AgeGroup?: string;
  Color?: string;
  Condition?: string;
  custom_label_0?: string;
  custom_label_1?: string;
  custom_label_2?: string;
  custom_label_3?: string;
  custom_label_4?: string;
  Gender?: string;
  Material?: string;
  MPN?: string;
  MPNStripPrefix?: string;
  Pattern?: string;
  GoogleShippingLabel?: string;
  Size?: string;
  AdwordsExcludedDestination?: string;
  AdwordsGrouping?: string;
  AdwordsLabels?: string;
  GoogleProductCategory?: string;
  PriceWithDiscount?: string;
  '1ozSizeLink'?: string;
  '3ozSizeLink'?: string;
  BatchSize?: string;
  BeardBag?: string;
  BelowItemNameMessage?: string;
  FullSizeLink?: string;
  GoogleExclude?: string;
  promotion_id?: string;
  tags?: string;
  TrialSizeLink?: string;
  InventoryLevel?: string; // Added for backward compatibility
  [key: string]: any; // For any additional fields
}

// Shopify Product types
export interface ShopifyProduct {
  'Title': string;
  'URL handle': string;
  'Description': string;
  'Vendor': string;
  'Product category': string;
  'Type': string;
  'Tags': string;
  'Published on online store': string;
  'Status': string;
  'SKU': string;
  'Barcode': string;
  'Option1 name': string;
  'Option1 value': string;
  'Option2 name': string;
  'Option2 value': string;
  'Option3 name': string;
  'Option3 value': string;
  'Price': string;
  'Price / International': string;
  'Compare-at price': string;
  'Compare-at price / International': string;
  'Cost per item': string;
  'Charge tax': string;
  'Tax code': string;
  'Inventory tracker': string;
  'Inventory quantity': string;
  'Continue selling when out of stock': string;
  'Weight value (grams)': string;
  'Weight unit for display': string;
  'Requires shipping': string;
  'Fulfillment service': string;
  'Product image URL': string;
  'Image position': string;
  'Image alt text': string;
  'Variant image URL': string;
  'Gift card': string;
  'SEO title': string;
  'SEO description': string;
  'Google Shopping / Google product category': string;
  'Google Shopping / Gender': string;
  'Google Shopping / Age group': string;
  'Google Shopping / MPN': string;
  'Google Shopping / AdWords Grouping': string;
  'Google Shopping / AdWords labels': string;
  'Google Shopping / Condition': string;
  'Google Shopping / Custom product': string;
  'Google Shopping / Custom label 0': string;
  'Google Shopping / Custom label 1': string;
  'Google Shopping / Custom label 2': string;
  'Google Shopping / Custom label 3': string;
  'Google Shopping / Custom label 4': string;
}
